from __future__ import annotations

from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Any
import json


@dataclass
class DefectAtom:
    atom_id: str
    group: str
    detector: str
    intervention_templates: list[str] = field(default_factory=list)
    status: str = "active"
    evidence: dict[str, Any] = field(default_factory=dict)
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class DefectRegistry:
    atoms: list[DefectAtom] = field(default_factory=list)
    version: str = "lean-rgc-defect-registry-v0.1"
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {"version": self.version, "metadata": self.metadata, "atoms": [a.to_dict() for a in self.atoms]}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "DefectRegistry":
        return cls(atoms=[DefectAtom(**a) for a in d.get("atoms", [])], version=d.get("version", "lean-rgc-defect-registry-v0.1"), metadata=d.get("metadata", {}))

    def save(self, path: str | Path) -> None:
        path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2, ensure_ascii=True, sort_keys=True), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> "DefectRegistry":
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))


def seed_defect_registry() -> DefectRegistry:
    atoms = [
        DefectAtom("unintroduced_forall", "exposure", "goal_has_forall", ["intros"], description="∀ target has not been exposed by intro/intros"),
        DefectAtom("unintroduced_imp", "exposure", "goal_has_imp", ["intros"], description="implication target has not been exposed"),
        DefectAtom("unsplit_and_target", "exposure", "target_is_and", ["constructor"], description="conjunction target awaits safe split"),
        DefectAtom("missing_and_projection", "premise", "has_and_hyp", ["simp_all", "exact h.left", "exact h.right"], description="conjunctive hypothesis needs projection"),
        DefectAtom("eq_reflexive_goal", "goal", "target_is_eq", ["rfl", "simp"], description="equality/reflexive-style goal"),
        DefectAtom("nat_arith_goal", "method", "has_nat_arith", ["omega", "norm_num", "simp"], description="Nat/Int arithmetic carrier"),
        DefectAtom("list_simp_goal", "method", "has_list", ["simp"], description="List simplification carrier"),
        DefectAtom("missing_rewrite_orientation", "premise", "rewrite_error_or_eq_goal", ["rw [?]", "rw [← ?]"], description="rewrite orientation/premise defect"),
        DefectAtom("missing_typeclass_instance", "type", "typeclass_error", ["infer_instance", "simp"], description="typeclass instance carrier"),
        DefectAtom("constructor_branch_debt", "search", "constructor_branching", ["constructor"], description="branching debt generated by constructor-like exposure"),
    ]
    return DefectRegistry(atoms=atoms, metadata={"source": "seed"})
